<?php
/**
 * Created by PhpStorm.
 * User: Konstantin
 * Date: 05.02.2017
 * Time: 17:41
 */

namespace app\components;

use yii\base\Widget;

class MenuCategoryWidget extends Widget
{
    public $template;
    public $data;
    public $tree;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if ($this->template === null)
        {
            $this->template = 'menu';
        }
        $this->template .= '.php';
    }

    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        return $this->template;
    }

}